"""Transformation assets."""

from .sqlmesh_transforms import (
    # Intermediate models
    int_team_rolling_stats,
    int_team_rolling_stats_lookup,
    int_team_season_stats,
    int_star_players,
    int_star_player_availability,
    int_team_star_player_features,
    int_game_injury_features,
    int_away_team_upset_tendency,
    int_team_streaks,
    int_team_rest_days,
    int_team_h2h_stats,
    int_team_opponent_quality,
    int_team_home_road_performance,
    # Momentum upstream models (individual - run each in Dagster)
    int_team_cumulative_fatigue,
    int_team_weighted_momentum,
    int_team_win_streak_quality,
    int_team_contextualized_streaks,
    int_team_recent_momentum_exponential,
    int_team_rivalry_indicators,
    int_team_opponent_specific_performance,
    int_team_opponent_tier_performance,
    int_team_opponent_tier_performance_by_home_away,
    int_team_performance_vs_opponent_quality_by_rest,
    int_team_performance_vs_similar_quality,
    int_team_quality_adjusted_performance,
    int_team_opponent_similarity_performance,
    int_team_recent_performance_weighted_by_opponent_quality,
    int_team_home_away_opp_qual,
    int_team_home_away_rest_performance,
    int_team_clutch_performance,
    int_team_blowout_performance,
    int_team_comeback_closeout_performance,
    int_team_overtime_performance,
    int_team_fourth_quarter_performance,
    int_team_game_outcome_quality,
    int_team_upset_resistance,
    int_team_favored_underdog_performance,
    int_team_recent_road_performance,
    int_team_season_timing_performance,
    int_team_playoff_race_context,
    int_team_form_divergence,
    int_team_performance_trends,
    int_team_recent_momentum,
    int_team_momentum_acceleration,
    int_team_performance_acceleration,
    int_team_recent_form_trend,
    int_team_performance_consistency,
    int_team_matchup_style_performance,
    int_team_performance_vs_similar_momentum,
    int_team_performance_vs_similar_rest_context,
    int_team_performance_in_rest_advantage_scenarios,
    int_team_performance_by_rest_combination,
    int_team_matchup_compatibility,
    int_team_performance_by_pace_context,
    # Momentum feature groups (pre-computed for efficient backfill)
    int_momentum_group_basic,
    int_momentum_group_h2h,
    int_momentum_group_opponent,
    int_momentum_group_context,
    int_momentum_group_trends,
    # Combined momentum features (joins the 5 groups)
    int_game_momentum_features,
    # Feature models
    game_features,
    team_features,
    team_injury_features,
)

__all__ = [
    # Intermediate models
    "int_team_rolling_stats",
    "int_team_rolling_stats_lookup",
    "int_team_season_stats",
    "int_star_players",
    "int_star_player_availability",
    "int_team_star_player_features",
    "int_game_injury_features",
    "int_away_team_upset_tendency",
    "int_team_streaks",
    "int_team_rest_days",
    "int_team_h2h_stats",
    "int_team_opponent_quality",
    "int_team_home_road_performance",
    # Momentum upstream models
    "int_team_cumulative_fatigue",
    "int_team_weighted_momentum",
    "int_team_win_streak_quality",
    "int_team_contextualized_streaks",
    "int_team_recent_momentum_exponential",
    "int_team_rivalry_indicators",
    "int_team_opponent_specific_performance",
    "int_team_opponent_tier_performance",
    "int_team_opponent_tier_performance_by_home_away",
    "int_team_performance_vs_opponent_quality_by_rest",
    "int_team_performance_vs_similar_quality",
    "int_team_quality_adjusted_performance",
    "int_team_opponent_similarity_performance",
    "int_team_recent_performance_weighted_by_opponent_quality",
    "int_team_home_away_opp_qual",
    "int_team_home_away_rest_performance",
    "int_team_clutch_performance",
    "int_team_blowout_performance",
    "int_team_comeback_closeout_performance",
    "int_team_overtime_performance",
    "int_team_fourth_quarter_performance",
    "int_team_game_outcome_quality",
    "int_team_upset_resistance",
    "int_team_favored_underdog_performance",
    "int_team_recent_road_performance",
    "int_team_season_timing_performance",
    "int_team_playoff_race_context",
    "int_team_form_divergence",
    "int_team_performance_trends",
    "int_team_recent_momentum",
    "int_team_momentum_acceleration",
    "int_team_performance_acceleration",
    "int_team_recent_form_trend",
    "int_team_performance_consistency",
    "int_team_matchup_style_performance",
    "int_team_performance_vs_similar_momentum",
    "int_team_performance_vs_similar_rest_context",
    "int_team_performance_in_rest_advantage_scenarios",
    "int_team_performance_by_rest_combination",
    "int_team_matchup_compatibility",
    "int_team_performance_by_pace_context",
    # Momentum feature groups
    "int_momentum_group_basic",
    "int_momentum_group_h2h",
    "int_momentum_group_opponent",
    "int_momentum_group_context",
    "int_momentum_group_trends",
    # Combined momentum features
    "int_game_momentum_features",
    # Feature models
    "game_features",
    "team_features",
    "team_injury_features",
]
