"""Feast feature definitions for NBA analytics platform."""

from datetime import timedelta
from feast import FeatureView, Field
from feast.types import Float64, Int32, Bool
from data_sources import game_features_source
from entities import game

# Game features feature view
game_features_fv = FeatureView(
    name="game_features",
    entities=[game],
    ttl=timedelta(days=365),  # Keep features for 1 year
    schema=[
        Field(name="home_rolling_5_ppg", dtype=Float64),
        Field(name="away_rolling_5_ppg", dtype=Float64),
        Field(name="home_rolling_5_win_pct", dtype=Float64),
        Field(name="away_rolling_5_win_pct", dtype=Float64),
        Field(name="home_rolling_5_opp_ppg", dtype=Float64),
        Field(name="away_rolling_5_opp_ppg", dtype=Float64),
        Field(name="home_rolling_10_ppg", dtype=Float64),
        Field(name="away_rolling_10_ppg", dtype=Float64),
        Field(name="home_rolling_10_win_pct", dtype=Float64),
        Field(name="away_rolling_10_win_pct", dtype=Float64),
        Field(name="ppg_diff_5", dtype=Float64),
        Field(name="win_pct_diff_5", dtype=Float64),
        Field(name="ppg_diff_10", dtype=Float64),
        Field(name="win_pct_diff_10", dtype=Float64),
        Field(name="home_season_win_pct", dtype=Float64),
        Field(name="away_season_win_pct", dtype=Float64),
        Field(name="season_win_pct_diff", dtype=Float64),
        Field(name="home_star_players_returning", dtype=Int32),
        Field(name="home_key_players_returning", dtype=Int32),
        Field(name="home_extended_returns", dtype=Int32),
        Field(name="home_total_return_impact", dtype=Float64),
        Field(name="home_max_days_since_return", dtype=Int32),
        Field(name="away_star_players_returning", dtype=Int32),
        Field(name="away_key_players_returning", dtype=Int32),
        Field(name="away_extended_returns", dtype=Int32),
        Field(name="away_total_return_impact", dtype=Float64),
        Field(name="away_max_days_since_return", dtype=Int32),
        Field(name="return_impact_diff", dtype=Float64),
        Field(name="home_star_players_out", dtype=Int32),
        Field(name="home_key_players_out", dtype=Int32),
        Field(name="home_star_players_doubtful", dtype=Int32),
        Field(name="home_key_players_doubtful", dtype=Int32),
        Field(name="home_star_players_questionable", dtype=Int32),
        Field(name="home_injury_impact_score", dtype=Float64),
        Field(name="home_injured_players_count", dtype=Int32),
        Field(name="home_has_key_injury", dtype=Bool),
        Field(name="away_star_players_out", dtype=Int32),
        Field(name="away_key_players_out", dtype=Int32),
        Field(name="away_star_players_doubtful", dtype=Int32),
        Field(name="away_key_players_doubtful", dtype=Int32),
        Field(name="away_star_players_questionable", dtype=Int32),
        Field(name="away_injury_impact_score", dtype=Float64),
        Field(name="away_injured_players_count", dtype=Int32),
        Field(name="away_has_key_injury", dtype=Bool),
        Field(name="injury_impact_diff", dtype=Float64),
        Field(name="star_players_out_diff", dtype=Int32),
        Field(name="injury_impact_x_form_diff", dtype=Float64),
        Field(name="away_injury_x_form", dtype=Float64),
        Field(name="home_injury_x_form", dtype=Float64),
        Field(name="home_injury_impact_ratio", dtype=Float64),
        Field(name="away_injury_impact_ratio", dtype=Float64),
        Field(name="home_win_streak", dtype=Int32),
        Field(name="home_loss_streak", dtype=Int32),
        Field(name="away_win_streak", dtype=Int32),
        Field(name="away_loss_streak", dtype=Int32),
        Field(name="home_momentum_score", dtype=Float64),
        Field(name="away_momentum_score", dtype=Float64),
        Field(name="home_rest_days", dtype=Int32),
        Field(name="home_back_to_back", dtype=Bool),
        Field(name="away_rest_days", dtype=Int32),
        Field(name="away_back_to_back", dtype=Bool),
        Field(name="rest_advantage", dtype=Int32),
        Field(name="home_form_divergence", dtype=Float64),
        Field(name="away_form_divergence", dtype=Float64),
        Field(name="home_h2h_win_pct", dtype=Float64),
        Field(name="home_h2h_recent_wins", dtype=Int32),
        Field(name="home_recent_opp_avg_win_pct", dtype=Float64),
        Field(name="away_recent_opp_avg_win_pct", dtype=Float64),
        Field(name="home_performance_vs_quality", dtype=Float64),
        Field(name="away_performance_vs_quality", dtype=Float64),
        Field(name="home_home_win_pct", dtype=Float64),
        Field(name="away_road_win_pct", dtype=Float64),
        Field(name="home_advantage", dtype=Float64),
    ],
    source=game_features_source,
    tags={"team": "ml", "domain": "nba", "version": "v1.0"},
)
