MODEL (
    name features_dev.game_features,
    kind VIEW,
    description 'ML-ready game features - view over marts.mart_game_features. No separate materialization; always reflects current mart. When you add columns to mart_game_features, backfill only the date range you need (e.g. last 5 years for ML).'
);

SELECT 
    game_id,
    game_date,
    home_team_id,
    away_team_id,
    
    -- Target variables
    home_win,
    home_score,
    away_score,
    point_spread,
    total_points,
    is_overtime,
    
    -- Home team rolling features
    home_rolling_5_ppg,
    home_rolling_5_opp_ppg,
    home_rolling_5_win_pct,
    home_rolling_5_apg,
    home_rolling_5_rpg,
    home_rolling_5_fg_pct,
    home_rolling_5_fg3_pct,
    home_rolling_5_efg_pct,
    home_rolling_5_ts_pct,
    home_rolling_5_off_rtg,
    home_rolling_5_def_rtg,
    home_rolling_5_net_rtg,
    home_rolling_5_pace,
    home_rolling_5_tov_rate,
    home_rolling_5_assist_rate,
    home_rolling_5_steal_rate,
    home_rolling_5_block_rate,
    home_rolling_5_ppg_stddev,
    home_rolling_5_opp_ppg_stddev,
    home_rolling_5_ppg_cv,
    home_rolling_5_opp_ppg_cv,
    home_rolling_10_ppg,
    home_rolling_10_win_pct,
    home_rolling_10_efg_pct,
    home_rolling_10_ts_pct,
    home_rolling_10_off_rtg,
    home_rolling_10_def_rtg,
    home_rolling_10_net_rtg,
    home_rolling_10_pace,
    home_rolling_10_tov_rate,
    home_rolling_10_assist_rate,
    home_rolling_10_steal_rate,
    home_rolling_10_block_rate,
    home_rolling_10_ppg_stddev,
    home_rolling_10_opp_ppg_stddev,
    home_rolling_10_ppg_cv,
    home_rolling_10_opp_ppg_cv,
    
    -- Away team rolling features
    away_rolling_5_ppg,
    away_rolling_5_opp_ppg,
    away_rolling_5_win_pct,
    away_rolling_5_apg,
    away_rolling_5_rpg,
    away_rolling_5_fg_pct,
    away_rolling_5_fg3_pct,
    away_rolling_5_efg_pct,
    away_rolling_5_ts_pct,
    away_rolling_5_off_rtg,
    away_rolling_5_def_rtg,
    away_rolling_5_net_rtg,
    away_rolling_5_pace,
    away_rolling_5_tov_rate,
    away_rolling_5_assist_rate,
    away_rolling_5_steal_rate,
    away_rolling_5_block_rate,
    away_rolling_5_ppg_stddev,
    away_rolling_5_opp_ppg_stddev,
    away_rolling_5_ppg_cv,
    away_rolling_5_opp_ppg_cv,
    away_rolling_10_ppg,
    away_rolling_10_win_pct,
    away_rolling_10_efg_pct,
    away_rolling_10_ts_pct,
    away_rolling_10_off_rtg,
    away_rolling_10_def_rtg,
    away_rolling_10_net_rtg,
    away_rolling_10_pace,
    away_rolling_10_tov_rate,
    away_rolling_10_assist_rate,
    away_rolling_10_steal_rate,
    away_rolling_10_block_rate,
    away_rolling_10_ppg_stddev,
    away_rolling_10_opp_ppg_stddev,
    away_rolling_10_ppg_cv,
    away_rolling_10_opp_ppg_cv,
    
    -- Differential features
    ppg_diff_5,
    win_pct_diff_5,
    fg_pct_diff_5,
    efg_pct_diff_5,
    ts_pct_diff_5,
    off_rtg_diff_5,
    def_rtg_diff_5,
    net_rtg_diff_5,
    pace_diff_5,
    tov_rate_diff_5,
    assist_rate_diff_5,
    steal_rate_diff_5,
    block_rate_diff_5,
    ppg_diff_10,
    win_pct_diff_10,
    efg_pct_diff_10,
    ts_pct_diff_10,
    off_rtg_diff_10,
    def_rtg_diff_10,
    net_rtg_diff_10,
    pace_diff_10,
    tov_rate_diff_10,
    assist_rate_diff_10,
    steal_rate_diff_10,
    block_rate_diff_10,
    -- Consistency differential features
    ppg_stddev_diff_5,
    opp_ppg_stddev_diff_5,
    ppg_cv_diff_5,
    opp_ppg_cv_diff_5,
    ppg_stddev_diff_10,
    opp_ppg_stddev_diff_10,
    ppg_cv_diff_10,
    opp_ppg_cv_diff_10,
    
    -- Season context
    home_season_win_pct,
    home_season_point_diff,
    home_wins_at_home,
    home_losses_at_home,
    away_season_win_pct,
    away_season_point_diff,
    away_wins_on_road,
    away_losses_on_road,
    
    -- Season differential
    season_win_pct_diff,
    season_point_diff_diff,
    
    -- Home team star player return features
    home_star_players_returning,
    home_key_players_returning,
    home_extended_returns,
    home_total_return_impact,
    home_max_days_since_return,
    home_avg_days_since_return,
    home_has_star_return,
    home_has_extended_return,
    
    -- Away team star player return features
    away_star_players_returning,
    away_key_players_returning,
    away_extended_returns,
    away_total_return_impact,
    away_max_days_since_return,
    away_avg_days_since_return,
    away_has_star_return,
    away_has_extended_return,
    
    -- Star return differential features
    star_return_advantage,
    return_impact_diff,
    
    -- Injury features
    home_star_players_out,
    home_key_players_out,
    home_star_players_doubtful,
    home_key_players_doubtful,
    home_star_players_questionable,
    home_injury_impact_score,
    home_injured_players_count,
    home_has_key_injury,
    away_star_players_out,
    away_key_players_out,
    away_star_players_doubtful,
    away_key_players_doubtful,
    away_star_players_questionable,
    away_injury_impact_score,
    away_injured_players_count,
    away_has_key_injury,
    injury_impact_diff,
    injury_advantage_home,
    star_players_out_diff,
    
    -- Feature interactions: Injury impact with other key features
    injury_impact_x_form_diff,
    away_injury_x_form,
    home_injury_x_form,
    home_injury_impact_ratio,
    away_injury_impact_ratio,
    
    -- Explicit injury penalty features
    home_injury_penalty_severe,
    away_injury_penalty_severe,
    home_injury_penalty_absolute,
    away_injury_penalty_absolute,
    
    -- NEW: Advanced feature interactions (Iteration 2 - 2026-01-25)
    injury_impact_x_rest_advantage,
    win_pct_diff_10_x_home_advantage,
    net_rtg_diff_10_x_rest_advantage,
    net_rtg_diff_10_x_home_advantage,
    off_rtg_diff_10_x_pace_diff_10,
    def_rtg_advantage_x_rest_advantage,
    -- NEW: Rest Advantage x Team Quality interactions (Iteration 19 - 2026-01-25)
    rest_advantage_x_win_pct_diff_10,
    home_rest_days_x_home_win_pct_10,
    away_rest_days_x_away_win_pct_10,
    -- NEW: Rest Quality interactions (Iteration 23 - 2026-01-25)
    -- Rest matters more after tough schedule (high SOS) than after easy schedule
    home_rest_days_x_home_sos_10,
    away_rest_days_x_away_sos_10,
    rest_advantage_x_sos_10_diff,
    form_divergence_win_pct_diff_10_x_rest_advantage,
    -- NEW: Back-to-back with travel impact features (Iteration 25 - 2026-01-25)
    -- Back-to-backs with travel are significantly harder than back-to-backs without travel
    home_back_to_back_with_travel,
    away_back_to_back_with_travel,
    back_to_back_travel_advantage,
    -- Travel fatigue features (Iteration 11)
    home_btb_travel_count_5,
    home_btb_travel_count_10,
    home_travel_fatigue_score_5,
    away_btb_travel_count_5,
    away_btb_travel_count_10,
    away_travel_fatigue_score_5,
    btb_travel_count_5_diff,
    btb_travel_count_10_diff,
    travel_fatigue_score_5_diff,
    home_btb_travel_x_win_pct_10,
    away_btb_travel_x_win_pct_10,
    home_btb_travel_x_rest_penalty,
    away_btb_travel_x_rest_penalty,
    
    -- NEW: Recent Head-to-Head features (Iteration 7 - 2026-01-25)
    home_h2h_win_pct_3,
    home_h2h_win_pct_5,
    home_h2h_avg_point_diff_3,
    home_h2h_avg_point_diff_5,
    home_h2h_momentum,
    -- NEW: Momentum × H2H interactions (Iteration 8 - 2026-01-26)
    -- Momentum and H2H history together are more predictive than either alone
    momentum_score_diff_x_h2h_win_pct_3,
    momentum_score_diff_x_h2h_win_pct_5,
    home_momentum_x_h2h_win_pct_3,
    home_momentum_x_h2h_win_pct_5,
    away_momentum_x_h2h_win_pct_3,
    away_momentum_x_h2h_win_pct_5,
    weighted_momentum_diff_5_x_h2h_win_pct_5,
    weighted_momentum_diff_10_x_h2h_win_pct_5,
    
    -- NEW: Win streak quality (Iteration 26 - 2026-01-27)
    -- Win streak length weighted by average opponent quality during the streak
    home_win_streak_quality,
    away_win_streak_quality,
    win_streak_quality_diff,
    -- NEW: Win streak quality × opponent quality interactions (Iteration 27 - 2026-01-27)
    -- Win streak quality matters more when facing strong opponents
    home_win_streak_quality_x_away_opponent_quality,
    away_win_streak_quality_x_home_opponent_quality,
    win_streak_quality_diff_x_opponent_quality_diff,
    
    -- NEW: Away team upset tendency (Iteration 3 - 2026-01-25)
    away_upset_tendency_season,
    away_upset_tendency_rolling,
    away_upset_sample_size_season,
    away_upset_sample_size_rolling,
    
    -- NEW: Rolling Schedule Strength (SOS) features (Iteration 9 - 2026-01-25)
    home_sos_5_rolling,
    away_sos_5_rolling,
    home_sos_10_rolling,
    away_sos_10_rolling,
    home_sos_5_weighted,
    away_sos_5_weighted,
    sos_5_diff,
    sos_10_diff,
    sos_5_weighted_diff,
    home_win_pct_vs_sos_10,
    away_win_pct_vs_sos_10,
    win_pct_vs_sos_10_diff,
    
    -- NEW: Clutch performance features (Iteration 12 - 2026-01-25)
    home_clutch_win_pct,
    home_clutch_game_count,
    home_clutch_avg_point_diff,
    away_clutch_win_pct,
    away_clutch_game_count,
    away_clutch_avg_point_diff,
    clutch_win_pct_diff,
    clutch_avg_point_diff_diff,
    -- Blowout performance features (Iteration 4 - 2026-01-25)
    -- Team performance in games decided by > 15 points (complementary to clutch performance)
    home_blowout_win_pct,
    home_blowout_game_count,
    home_blowout_avg_point_diff,
    home_blowout_frequency,
    away_blowout_win_pct,
    away_blowout_game_count,
    away_blowout_avg_point_diff,
    away_blowout_frequency,
    blowout_win_pct_diff,
    blowout_avg_point_diff_diff,
    blowout_frequency_diff,
    -- NEW: Comeback/closeout performance features (Iteration 3 - 2026-01-26)
    -- Comeback performance: ability to win close games (comeback ability)
    -- Closeout performance: ability to win games with large margins (closeout ability)
    home_comeback_win_pct,
    home_comeback_game_count,
    home_comeback_avg_point_diff,
    home_closeout_win_pct,
    home_closeout_game_count,
    home_closeout_avg_point_diff,
    away_comeback_win_pct,
    away_comeback_game_count,
    away_comeback_avg_point_diff,
    away_closeout_win_pct,
    away_closeout_game_count,
    away_closeout_avg_point_diff,
    comeback_win_pct_diff,
    closeout_win_pct_diff,
    comeback_avg_point_diff_diff,
    closeout_avg_point_diff_diff,
    -- Overtime performance features (Iteration 36 - 2026-01-25)
    home_overtime_win_pct,
    home_overtime_game_count,
    home_overtime_avg_point_diff,
    away_overtime_win_pct,
    away_overtime_game_count,
    away_overtime_avg_point_diff,
    overtime_win_pct_diff,
    overtime_avg_point_diff_diff,
    
    -- Recent road performance features (Iteration 2 - 2026-01-26)
    -- Away team's performance in last 5/10 road games - captures recent road form
    away_recent_road_win_pct_5,
    away_recent_road_game_count_5,
    away_recent_road_avg_point_diff_5,
    away_recent_road_win_pct_10,
    away_recent_road_game_count_10,
    away_recent_road_avg_point_diff_10,
    
    -- Form divergence features (Iteration 37 - 2026-01-25)
    -- Recent performance vs season average - captures teams trending above/below their baseline
    home_form_divergence_win_pct_5,
    home_form_divergence_ppg_5,
    home_form_divergence_opp_ppg_5,
    home_form_divergence_net_rtg_5,
    home_form_divergence_win_pct_10,
    home_form_divergence_ppg_10,
    home_form_divergence_opp_ppg_10,
    home_form_divergence_net_rtg_10,
    away_form_divergence_win_pct_5,
    away_form_divergence_ppg_5,
    away_form_divergence_opp_ppg_5,
    away_form_divergence_net_rtg_5,
    away_form_divergence_win_pct_10,
    away_form_divergence_ppg_10,
    away_form_divergence_opp_ppg_10,
    away_form_divergence_net_rtg_10,
    home_form_divergence_magnitude_win_pct_5,
    home_form_divergence_magnitude_win_pct_10,
    away_form_divergence_magnitude_win_pct_5,
    away_form_divergence_magnitude_win_pct_10,
    form_divergence_win_pct_diff_5,
    form_divergence_ppg_diff_5,
    form_divergence_net_rtg_diff_5,
    form_divergence_win_pct_diff_10,
    form_divergence_ppg_diff_10,
    form_divergence_net_rtg_diff_10,
    
    -- NEW: Momentum weighted by opponent quality (Iteration 21 - 2026-01-25)
    home_weighted_momentum_5,
    home_weighted_momentum_10,
    away_weighted_momentum_5,
    away_weighted_momentum_10,
    weighted_momentum_diff_5,
    weighted_momentum_diff_10,
    -- Iteration 18: Recent performance weighted by opponent quality
    home_weighted_win_pct_5,
    home_weighted_win_pct_10,
    home_weighted_point_diff_5,
    home_weighted_point_diff_10,
    home_weighted_net_rtg_5,
    home_weighted_net_rtg_10,
    away_weighted_win_pct_5,
    away_weighted_win_pct_10,
    away_weighted_point_diff_5,
    away_weighted_point_diff_10,
    away_weighted_net_rtg_5,
    away_weighted_net_rtg_10,
    weighted_win_pct_diff_5,
    weighted_win_pct_diff_10,
    weighted_point_diff_diff_5,
    weighted_point_diff_diff_10,
    weighted_net_rtg_diff_5,
    weighted_net_rtg_diff_10,
    
    -- NEW: Form divergence features (Iteration 22 - 2026-01-25)
    -- Recent performance vs season average - captures when teams are playing hot or cold
    home_win_pct_divergence_5,
    home_win_pct_divergence_10,
    home_net_rtg_divergence_5,
    home_net_rtg_divergence_10,
    home_ppg_divergence_5,
    home_ppg_divergence_10,
    home_opp_ppg_divergence_5,
    home_opp_ppg_divergence_10,
    home_off_rtg_divergence_5,
    home_off_rtg_divergence_10,
    home_def_rtg_divergence_5,
    home_def_rtg_divergence_10,
    away_win_pct_divergence_5,
    away_win_pct_divergence_10,
    away_net_rtg_divergence_5,
    away_net_rtg_divergence_10,
    away_ppg_divergence_5,
    away_ppg_divergence_10,
    away_opp_ppg_divergence_5,
    away_opp_ppg_divergence_10,
    away_off_rtg_divergence_5,
    away_off_rtg_divergence_10,
    away_def_rtg_divergence_5,
    away_def_rtg_divergence_10,
    win_pct_divergence_diff_5,
    win_pct_divergence_diff_10,
    net_rtg_divergence_diff_5,
    net_rtg_divergence_diff_10,
    ppg_divergence_diff_5,
    ppg_divergence_diff_10,
    -- Home/away splits by opponent quality (Iteration 24)
    home_win_pct_vs_strong,
    home_win_pct_vs_weak,
    away_win_pct_vs_strong,
    away_win_pct_vs_weak,
    win_pct_vs_strong_diff,
    win_pct_vs_weak_diff,
    -- Home/away performance by rest days (Iteration 28)
    home_win_pct_by_rest_bucket,
    away_win_pct_by_rest_bucket,
    rest_bucket_win_pct_diff,
    -- Performance trends (Iteration 29): Rate of change between 5-game and 10-game windows
    -- Positive = improving, Negative = declining
    home_win_pct_trend,
    home_net_rtg_trend,
    home_ppg_trend,
    home_off_rtg_trend,
    home_efg_pct_trend,
    home_ts_pct_trend,
    home_opp_ppg_trend,
    home_def_rtg_trend,
    away_win_pct_trend,
    away_net_rtg_trend,
    away_ppg_trend,
    away_off_rtg_trend,
    away_efg_pct_trend,
    away_ts_pct_trend,
    away_opp_ppg_trend,
    away_def_rtg_trend,
    -- Trend differentials: Positive = home team trending better (favor home)
    win_pct_trend_diff,
    net_rtg_trend_diff,
    ppg_trend_diff,
    off_rtg_trend_diff,
    efg_pct_trend_diff,
    ts_pct_trend_diff,
    opp_ppg_trend_diff,
    def_rtg_trend_diff,
    -- Recent momentum (Iteration 3): Rate of change between 3-game and 5-game windows - more immediate than 5-game vs 10-game trends
    -- Positive = improving (last 3 games better than last 5), Negative = declining
    home_recent_win_pct_momentum,
    home_recent_net_rtg_momentum,
    home_recent_ppg_momentum,
    home_recent_off_rtg_momentum,
    home_recent_efg_pct_momentum,
    home_recent_ts_pct_momentum,
    home_recent_opp_ppg_momentum,
    home_recent_def_rtg_momentum,
    away_recent_win_pct_momentum,
    away_recent_net_rtg_momentum,
    away_recent_ppg_momentum,
    away_recent_off_rtg_momentum,
    away_recent_efg_pct_momentum,
    away_recent_ts_pct_momentum,
    away_recent_opp_ppg_momentum,
    away_recent_def_rtg_momentum,
    -- Recent momentum differentials: Positive = home team has better recent momentum (favor home)
    recent_win_pct_momentum_diff,
    recent_net_rtg_momentum_diff,
    recent_ppg_momentum_diff,
    recent_off_rtg_momentum_diff,
    recent_efg_pct_momentum_diff,
    recent_ts_pct_momentum_diff,
    recent_opp_ppg_momentum_diff,
    recent_def_rtg_momentum_diff,
    -- Matchup style performance (Iteration 30): Team performance vs different opponent styles
    -- Home team performance vs different styles
    home_win_pct_vs_fast_paced,
    home_win_pct_vs_slow_paced,
    home_win_pct_vs_high_scoring,
    home_win_pct_vs_defensive,
    -- Away team performance vs different styles
    away_win_pct_vs_fast_paced,
    away_win_pct_vs_slow_paced,
    away_win_pct_vs_high_scoring,
    away_win_pct_vs_defensive,
    -- Differential features (home - away)
    win_pct_vs_fast_paced_diff,
    win_pct_vs_slow_paced_diff,
    win_pct_vs_high_scoring_diff,
    win_pct_vs_defensive_diff,
    -- Rivalry indicators (Iteration 31): Matchup frequency and intensity
    rivalry_total_matchups,
    rivalry_recent_matchups,
    -- Opponent-specific performance (Iteration 7): Team performance vs specific opponents in different contexts
    home_vs_opponent_home_win_pct,
    home_vs_opponent_home_games,
    home_vs_opponent_home_avg_point_diff,
    home_vs_opponent_away_win_pct,
    home_vs_opponent_away_games,
    home_vs_opponent_away_avg_point_diff,
    away_vs_opponent_home_win_pct,
    away_vs_opponent_home_games,
    away_vs_opponent_home_avg_point_diff,
    away_vs_opponent_away_win_pct,
    away_vs_opponent_away_games,
    away_vs_opponent_away_avg_point_diff,
    opponent_specific_win_pct_diff,
    opponent_specific_avg_point_diff_diff,
    rivalry_avg_point_margin,
    rivalry_close_game_pct,
    rivalry_very_close_game_pct,
    rivalry_recent_close_game_pct,
    rivalry_recent_avg_margin,
    -- Opponent similarity performance (Iteration 2): Team performance vs opponents with similar characteristics
    home_win_pct_vs_similar_opponents,
    home_similar_opponent_game_count,
    home_avg_point_diff_vs_similar_opponents,
    away_win_pct_vs_similar_opponents,
    away_similar_opponent_game_count,
    away_avg_point_diff_vs_similar_opponents,
    current_game_similarity_score,
    win_pct_vs_similar_opponents_diff,
    avg_point_diff_vs_similar_opponents_diff,
    -- Performance vs similar quality opponents (Iteration 15): Team performance vs opponents with similar win_pct or net_rtg
    home_win_pct_vs_similar_quality,
    home_avg_point_diff_vs_similar_quality,
    home_similar_quality_game_count,
    away_win_pct_vs_similar_quality,
    away_avg_point_diff_vs_similar_quality,
    away_similar_quality_game_count,
    is_current_game_similar_quality,
    win_pct_vs_similar_quality_diff,
    avg_point_diff_vs_similar_quality_diff,
    -- Performance vs similar momentum opponents (Iteration 28): Team performance vs opponents with similar recent momentum
    home_win_pct_vs_similar_momentum,
    home_avg_point_diff_vs_similar_momentum,
    home_similar_momentum_game_count,
    away_win_pct_vs_similar_momentum,
    away_avg_point_diff_vs_similar_momentum,
    away_similar_momentum_game_count,
    is_current_game_similar_momentum,
    win_pct_vs_similar_momentum_diff,
    avg_point_diff_vs_similar_momentum_diff,
    -- Iteration 33: Performance vs similar rest context features
    home_win_pct_vs_similar_rest,
    home_avg_point_diff_vs_similar_rest,
    home_similar_rest_game_count,
    away_win_pct_vs_similar_rest,
    away_avg_point_diff_vs_similar_rest,
    away_similar_rest_game_count,
    is_current_game_similar_rest_context,
    win_pct_vs_similar_rest_diff,
    avg_point_diff_vs_similar_rest_diff,
    -- Iteration 35: Performance in rest advantage scenarios features
    -- Captures how teams perform when they have rest advantage vs rest disadvantage
    home_win_pct_well_rested_vs_tired,
    home_avg_point_diff_well_rested_vs_tired,
    home_well_rested_vs_tired_count,
    home_win_pct_well_rested_vs_moderate,
    home_avg_point_diff_well_rested_vs_moderate,
    home_well_rested_vs_moderate_count,
    home_win_pct_moderate_vs_tired,
    home_avg_point_diff_moderate_vs_tired,
    home_moderate_vs_tired_count,
    home_win_pct_with_rest_advantage,
    home_avg_point_diff_with_rest_advantage,
    home_with_rest_advantage_count,
    away_win_pct_well_rested_vs_tired,
    away_avg_point_diff_well_rested_vs_tired,
    away_well_rested_vs_tired_count,
    away_win_pct_well_rested_vs_moderate,
    away_avg_point_diff_well_rested_vs_moderate,
    away_well_rested_vs_moderate_count,
    away_win_pct_moderate_vs_tired,
    away_avg_point_diff_moderate_vs_tired,
    away_moderate_vs_tired_count,
    away_win_pct_with_rest_advantage,
    away_avg_point_diff_with_rest_advantage,
    away_with_rest_advantage_count,
    is_well_rested_vs_tired,
    is_well_rested_vs_moderate,
    is_moderate_vs_tired,
    is_rest_advantage_scenario,
    win_pct_well_rested_vs_tired_diff,
    win_pct_well_rested_vs_moderate_diff,
    win_pct_moderate_vs_tired_diff,
    win_pct_with_rest_advantage_diff,
    -- Iteration 62: Team performance by rest day combination (specific home/away rest combinations)
    -- Captures how teams perform in games with specific rest day combinations (e.g., home 2 days rest vs away 1 day rest)
    home_win_pct_by_rest_combination,
    home_avg_point_diff_by_rest_combination,
    home_rest_combination_count,
    away_win_pct_by_rest_combination,
    away_avg_point_diff_by_rest_combination,
    away_rest_combination_count,
    rest_combination_win_pct_diff,
    rest_combination_point_diff_diff,
    -- Iteration 34: Performance vs similar rest context × team quality interactions
    -- Better teams may perform differently in similar rest contexts than weaker teams
    home_win_pct_vs_similar_rest_x_home_win_pct_10,
    away_win_pct_vs_similar_rest_x_away_win_pct_10,
    win_pct_vs_similar_rest_diff_x_win_pct_diff_10,
    is_current_game_similar_rest_context_x_win_pct_diff_10,
    -- Iteration 36: Performance vs opponent quality by rest days
    -- Captures how teams perform vs strong/weak opponents when they have different rest levels
    home_win_pct_vs_strong_by_rest,
    home_games_vs_strong_by_rest,
    home_win_pct_vs_weak_by_rest,
    home_games_vs_weak_by_rest,
    away_win_pct_vs_strong_by_rest,
    away_games_vs_strong_by_rest,
    away_win_pct_vs_weak_by_rest,
    away_games_vs_weak_by_rest,
    win_pct_vs_strong_by_rest_diff,
    win_pct_vs_weak_by_rest_diff,
    -- Iteration 38: Opponent tier performance by home/away context (team performance vs opponent quality tiers split by home/away)
    home_win_pct_vs_opponent_tier_at_home,
    home_avg_point_diff_vs_opponent_tier_at_home,
    home_game_count_vs_opponent_tier_at_home,
    home_win_pct_vs_opponent_tier_on_road,
    home_avg_point_diff_vs_opponent_tier_on_road,
    home_game_count_vs_opponent_tier_on_road,
    away_win_pct_vs_opponent_tier_at_home,
    away_avg_point_diff_vs_opponent_tier_at_home,
    away_game_count_vs_opponent_tier_at_home,
    away_win_pct_vs_opponent_tier_on_road,
    away_avg_point_diff_vs_opponent_tier_on_road,
    away_game_count_vs_opponent_tier_on_road,
    win_pct_vs_opponent_tier_home_away_diff,
    avg_point_diff_vs_opponent_tier_home_away_diff,
    -- Season progress (Iteration 30): Game context (early/mid/late season)
    days_since_season_start,
    season_progress,
    is_late_season,
    -- Playoff race context (Iteration 32): Game importance and urgency
    home_playoff_rank,
    home_is_in_playoff_position,
    home_games_back_from_cutoff,
    home_win_pct_diff_from_cutoff,
    home_is_close_to_cutoff,
    home_is_fighting_for_playoff_spot,
    away_playoff_rank,
    away_is_in_playoff_position,
    away_games_back_from_cutoff,
    away_win_pct_diff_from_cutoff,
    away_is_close_to_cutoff,
    away_is_fighting_for_playoff_spot,
    playoff_rank_diff,
    playoff_position_diff,
    games_back_from_cutoff_diff,
    win_pct_diff_from_cutoff_diff,
    is_playoff_race_game,
    is_high_stakes_game,
    -- Iteration 43: Season timing performance features (team performance by season phase)
    -- Early season performance (first 20 games)
    home_early_season_win_pct,
    home_early_season_game_count,
    home_early_season_avg_point_diff,
    -- Mid season performance (games 21-60)
    home_mid_season_win_pct,
    home_mid_season_game_count,
    home_mid_season_avg_point_diff,
    -- Late season performance (games 61-82)
    home_late_season_win_pct,
    home_late_season_game_count,
    home_late_season_avg_point_diff,
    -- Playoff push performance (last 10 games)
    home_playoff_push_win_pct,
    home_playoff_push_game_count,
    home_playoff_push_avg_point_diff,
    -- Current game season phase indicators
    is_home_early_season,
    is_home_mid_season,
    is_home_late_season,
    is_home_playoff_push,
    -- Away team season timing features
    away_early_season_win_pct,
    away_early_season_game_count,
    away_early_season_avg_point_diff,
    away_mid_season_win_pct,
    away_mid_season_game_count,
    away_mid_season_avg_point_diff,
    away_late_season_win_pct,
    away_late_season_game_count,
    away_late_season_avg_point_diff,
    away_playoff_push_win_pct,
    away_playoff_push_game_count,
    away_playoff_push_avg_point_diff,
    is_away_early_season,
    is_away_mid_season,
    is_away_late_season,
    is_away_playoff_push,
    -- Differential features (home - away)
    early_season_win_pct_diff,
    early_season_avg_point_diff_diff,
    mid_season_win_pct_diff,
    mid_season_avg_point_diff_diff,
    late_season_win_pct_diff,
    late_season_avg_point_diff_diff,
    playoff_push_win_pct_diff,
    playoff_push_avg_point_diff_diff,
    -- Iteration 34: Game outcome quality features (how teams win/lose - close vs blowouts)
    home_avg_margin_in_wins_5,
    home_avg_margin_in_losses_5,
    home_close_game_win_pct_5,
    home_blowout_game_win_pct_5,
    home_avg_margin_in_wins_10,
    home_avg_margin_in_losses_10,
    home_close_game_win_pct_10,
    home_blowout_game_win_pct_10,
    away_avg_margin_in_wins_5,
    away_avg_margin_in_losses_5,
    away_close_game_win_pct_5,
    away_blowout_game_win_pct_5,
    away_avg_margin_in_wins_10,
    away_avg_margin_in_losses_10,
    away_close_game_win_pct_10,
    away_blowout_game_win_pct_10,
    avg_margin_in_wins_diff_5,
    avg_margin_in_losses_diff_5,
    close_game_win_pct_diff_5,
    blowout_game_win_pct_diff_5,
    avg_margin_in_wins_diff_10,
    avg_margin_in_losses_diff_10,
    close_game_win_pct_diff_10,
    blowout_game_win_pct_diff_10,
    -- Iteration 35: Contextualized streak features (streaks weighted by opponent quality and home/away context)
    home_weighted_win_streak,
    home_weighted_loss_streak,
    home_win_streak_avg_opponent_quality,
    home_loss_streak_avg_opponent_quality,
    away_weighted_win_streak,
    away_weighted_loss_streak,
    away_win_streak_avg_opponent_quality,
    away_loss_streak_avg_opponent_quality,
    weighted_win_streak_diff,
    weighted_loss_streak_diff,
    win_streak_avg_opponent_quality_diff,
    loss_streak_avg_opponent_quality_diff,
    -- Iteration 38: Upset resistance features (teams that rarely lose when favored, frequently win when underdogs)
    home_favorite_win_pct,
    home_favorite_game_count,
    home_underdog_win_pct,
    home_underdog_game_count,
    home_upset_resistance_score,
    away_favorite_win_pct,
    away_favorite_game_count,
    away_underdog_win_pct,
    away_underdog_game_count,
    away_upset_resistance_score,
    favorite_win_pct_diff,
    underdog_win_pct_diff,
    upset_resistance_score_diff,
    -- Iteration 4: Quality-adjusted performance features - captures strength of recent wins/losses
    home_avg_opponent_strength_in_wins_5,
    home_avg_opponent_strength_in_losses_5,
    home_avg_opponent_strength_5,
    home_quality_adjusted_win_pct_5,
    home_avg_point_diff_in_wins_5,
    home_avg_point_diff_in_losses_5,
    home_wins_count_5,
    home_losses_count_5,
    home_total_games_5,
    home_avg_opponent_strength_in_wins_10,
    home_avg_opponent_strength_in_losses_10,
    home_avg_opponent_strength_10,
    home_quality_adjusted_win_pct_10,
    home_avg_point_diff_in_wins_10,
    home_avg_point_diff_in_losses_10,
    home_wins_count_10,
    home_losses_count_10,
    home_total_games_10,
    away_avg_opponent_strength_in_wins_5,
    away_avg_opponent_strength_in_losses_5,
    away_avg_opponent_strength_5,
    away_quality_adjusted_win_pct_5,
    away_avg_point_diff_in_wins_5,
    away_avg_point_diff_in_losses_5,
    away_wins_count_5,
    away_losses_count_5,
    away_total_games_5,
    away_avg_opponent_strength_in_wins_10,
    away_avg_opponent_strength_in_losses_10,
    away_avg_opponent_strength_10,
    away_quality_adjusted_win_pct_10,
    away_avg_point_diff_in_wins_10,
    away_avg_point_diff_in_losses_10,
    away_wins_count_10,
    away_losses_count_10,
    away_total_games_10,
    quality_adjusted_win_pct_diff_5,
    quality_adjusted_win_pct_diff_10,
    avg_opponent_strength_diff_5,
    avg_opponent_strength_diff_10,
    -- Iteration 1: Recent form trend features (comparing recent 3 vs recent 5 games)
    -- Captures whether teams are improving or declining (direction of change)
    home_form_trend_win_pct,
    home_form_trend_point_diff,
    away_form_trend_win_pct,
    away_form_trend_point_diff,
    form_trend_win_pct_diff,
    form_trend_point_diff_diff,
    -- Iteration 5: Momentum acceleration features (rate of change in momentum)
    -- Captures whether momentum is accelerating or decelerating
    home_momentum_acceleration,
    away_momentum_acceleration,
    momentum_acceleration_diff,
    -- Iteration 52: Performance acceleration features (comparing recent 3 games to previous 3 games)
    -- Captures rate of change in performance - teams improving vs declining
    home_win_pct_acceleration,
    home_point_diff_acceleration,
    home_ppg_acceleration,
    home_defensive_acceleration,
    home_net_rtg_acceleration,
    away_win_pct_acceleration,
    away_point_diff_acceleration,
    away_ppg_acceleration,
    away_defensive_acceleration,
    away_net_rtg_acceleration,
    win_pct_acceleration_diff,
    point_diff_acceleration_diff,
    ppg_acceleration_diff,
    defensive_acceleration_diff,
    net_rtg_acceleration_diff,
    -- Iteration 72: Exponential-weighted momentum features (weights most recent games exponentially more)
    -- This captures current form better than simple rolling averages by emphasizing recent games
    home_exp_weighted_win_pct_10,
    home_exp_weighted_point_diff_10,
    home_exp_weighted_ppg_10,
    home_exp_weighted_opp_ppg_10,
    home_exp_weighted_win_pct_5,
    home_exp_weighted_point_diff_5,
    away_exp_weighted_win_pct_10,
    away_exp_weighted_point_diff_10,
    away_exp_weighted_ppg_10,
    away_exp_weighted_opp_ppg_10,
    away_exp_weighted_win_pct_5,
    away_exp_weighted_point_diff_5,
    exp_weighted_win_pct_diff_10,
    exp_weighted_point_diff_diff_10,
    exp_weighted_ppg_diff_10,
    exp_weighted_opp_ppg_diff_10,
    exp_weighted_win_pct_diff_5,
    exp_weighted_point_diff_diff_5,
    -- Iteration 79: Cumulative fatigue features - capture game density over recent periods
    home_games_in_last_7_days,
    home_games_in_last_10_days,
    home_games_in_last_14_days,
    home_avg_rest_days_last_7_days,
    home_avg_rest_days_last_10_days,
    home_game_density_7_days,
    home_game_density_10_days,
    away_games_in_last_7_days,
    away_games_in_last_10_days,
    away_games_in_last_14_days,
    away_avg_rest_days_last_7_days,
    away_avg_rest_days_last_10_days,
    away_game_density_7_days,
    away_game_density_10_days,
    games_in_last_7_days_diff,
    games_in_last_10_days_diff,
    games_in_last_14_days_diff,
    avg_rest_days_last_7_days_diff,
    avg_rest_days_last_10_days_diff,
    game_density_7_days_diff,
    game_density_10_days_diff,
    -- Iteration 54: Team performance by pace context (fast-paced vs slow-paced games)
    home_fast_pace_win_pct,
    home_fast_pace_game_count,
    home_fast_pace_avg_point_diff,
    home_slow_pace_win_pct,
    home_slow_pace_game_count,
    home_slow_pace_avg_point_diff,
    away_fast_pace_win_pct,
    away_fast_pace_game_count,
    away_fast_pace_avg_point_diff,
    away_slow_pace_win_pct,
    away_slow_pace_game_count,
    away_slow_pace_avg_point_diff,
    fast_pace_win_pct_diff,
    fast_pace_avg_point_diff_diff,
    slow_pace_win_pct_diff,
    slow_pace_avg_point_diff_diff,
    -- Iteration 17: Team matchup compatibility features
    -- Captures how well two teams' styles match up in the current game
    pace_difference,
    pace_compatibility_score,
    home_off_vs_away_def_compatibility,
    away_off_vs_home_def_compatibility,
    style_matchup_advantage,
    net_rtg_difference,
    net_rtg_compatibility_score,
    
    -- Iteration 19: Matchup compatibility × team quality interactions
    style_matchup_advantage_x_win_pct_diff_10,
    style_matchup_advantage_x_net_rtg_diff_10,
    pace_compatibility_x_win_pct_diff_10,
    home_off_vs_away_def_compatibility_x_win_pct_diff_10,
    away_off_vs_home_def_compatibility_x_win_pct_diff_10,
    
    -- Iteration 23: Recent form vs season average divergence (momentum vs regression to mean)
    home_form_vs_season_divergence_10,
    away_form_vs_season_divergence_10,
    form_vs_season_divergence_diff_10,
    home_net_rtg_vs_season_divergence_10,
    away_net_rtg_vs_season_divergence_10,
    net_rtg_vs_season_divergence_diff_10,
    
    CURRENT_TIMESTAMP as updated_at
    
FROM marts.mart_game_features
